# Generated by Django 5.0 on 2024-03-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
