# Generated by Django 5.0 on 2024-03-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
