# Generated by Django 5.0 on 2024-03-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_id',
        ),
    ]
