# Generated by Django 5.0 on 2024-03-02 20:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование оборудования')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Описание')),
                ('data_cupil', models.CharField(default='', max_length=255, verbose_name='Дата приобретение')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование услуги')),
                ('about', models.CharField(default='No description provided', max_length=500, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО врача')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения врача')),
                ('image', models.ImageField(default='', null=True, upload_to='doctor_images/', verbose_name='Фотография врача')),
                ('bio', models.TextField(default='', null=True, verbose_name='Информация о враче')),
                ('achievements', models.CharField(default='', max_length=255, null=True, verbose_name='Достижения врача')),
                ('certificates', models.CharField(default='', max_length=255, null=True, verbose_name='Сертификаты врача')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя')),
                ('specialization_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='main.specializationcategory', verbose_name='Категория специальности')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Отзыв')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField(verbose_name='История болезни')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема ')),
                ('time', models.CharField(max_length=5, verbose_name='Время приема ')),
                ('non_registered_patient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя незарегистрированного пациента')),
                ('non_registered_patient_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт незарегистрированного пациента')),
                ('non_registered_patient_indevid_intevicat_nomer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(100000000000)], verbose_name='ИИН ПАЦИНЕТА')),
                ('patient_info', models.CharField(max_length=10000, verbose_name='Инфо о пациенте ')),
                ('comed', models.BooleanField(default=False, verbose_name='Пациент прибыл')),
                ('declined', models.BooleanField(default=False, verbose_name='Пациент отказался')),
                ('no_show', models.BooleanField(default=False, verbose_name='Пациент не пришел')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='Доктор ')),
                ('patient_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
                ('services', models.ManyToManyField(to='main.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_text', models.TextField(verbose_name='Текст диагноза')),
                ('date_diagnosed', models.DateTimeField(auto_now_add=True, verbose_name='Дата диагноза')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reception', verbose_name='Прием')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_text', models.TextField(verbose_name='Описание лечения')),
                ('date_prescribed', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения лечения')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diagnosis', verbose_name='Диагноз')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_schedule', models.TextField(verbose_name='График работы')),
                ('patient_acceptance_schedule', models.TextField(verbose_name='График приема пациентов')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='main.doctor', verbose_name='Врач')),
            ],
        ),
    ]
