# Generated by Django 5.0 on 2024-03-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='patient_info',
            field=models.CharField(max_length=10000, null=True, verbose_name='Инфо о пациенте '),
        ),
    ]
