# Generated by Django 5.0 on 2024-03-05 19:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reception_patient_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тренажера')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='full_name',
        ),
        migrations.AddField(
            model_name='reception',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение записи'),
        ),
        migrations.AddField(
            model_name='reception',
            name='payment_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение оплаты'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='date',
            field=models.DateField(verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='non_registered_patient_indevid_intevicat_nomer',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(0)], verbose_name='ИИН ПАЦИЕНТА'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='patient_info',
            field=models.CharField(max_length=10000, null=True, verbose_name='Инфо о пациенте'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='time',
            field=models.CharField(max_length=5, verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(default='Уточняйте у администратора', max_length=100, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='Masseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя массажиста')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения врача')),
                ('image', models.ImageField(default='', null=True, upload_to='doctor_images/', verbose_name='Фотография врача')),
                ('bio', models.TextField(default='', null=True, verbose_name='Информация о враче')),
                ('specialization_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masseurs', to='main.specializationcategory', verbose_name='Категория специальности')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masseur', to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Массажист',
                'verbose_name_plural': 'Массажисты',
            },
        ),
        migrations.AddField(
            model_name='reception',
            name='masseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.masseur', verbose_name='Массажист'),
        ),
        migrations.AddField(
            model_name='reception',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trainingequipment', verbose_name='Тренажер'),
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
