# Generated by Django 5.0 on 2024-03-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trainingequipment_remove_doctor_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user_profile',
            new_name='doctors_name',
        ),
    ]
