# Generated by Django 5.0 on 2024-03-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_profile_doctor_doctors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='patient_info',
        ),
    ]
