# Generated by Django 5.0 on 2024-03-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reception_patient_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='requires_massage',
            field=models.BooleanField(default=False, verbose_name='Требуется массаж'),
        ),
    ]
