# Generated by Django 5.0 on 2024-03-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reception_requires_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masseur',
            old_name='user_profile',
            new_name='masseur_name',
        ),
        migrations.RemoveField(
            model_name='masseur',
            name='name',
        ),
    ]
