# Generated by Django 5.0 on 2024-03-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_user_profile_masseur_masseur_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='services',
            field=models.ManyToManyField(null=True, to='main.service', verbose_name='Услуги'),
        ),
    ]
