# Generated by Django 5.0 on 2024-03-07 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_reception_doctor_alter_reception_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='date_diagnosed',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='date_prescribed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата назначения'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='treatment_text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание лечения'),
        ),
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
    ]
