# Generated by Django 5.0 on 2024-03-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_diagnosis_date_diagnosed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='inventory_number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='last_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего обслуживания'),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_qr/', verbose_name='QR Код'),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='status',
            field=models.CharField(choices=[('working', 'Рабочее'), ('repair', 'На ремонте'), ('out_of_service', 'Выведено из эксплуатации')], default='working', max_length=15, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='EquipmentServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Дата обслуживания')),
                ('description', models.TextField(verbose_name='Описание обслуживания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicalequipment')),
            ],
        ),
    ]
