# Generated by Django 5.0 on 2024-03-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_medicalequipment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
