# Generated by Django 5.0 on 2024-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_medicalequipment_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='status',
            field=models.CharField(choices=[('рабочий', 'Рабочее'), ('на ремонте', 'На ремонте'), ('не работает', 'Выведено из эксплуатации')], default='Рабочее', max_length=15, verbose_name='Статус'),
        ),
    ]
