# Generated by Django 5.0 on 2024-03-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_telegrambot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBot',
        ),
    ]
