# Generated by Django 5.0 on 2024-03-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_telegrambot'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='service_images/', verbose_name='Фотография услуг'),
        ),
    ]
