# Generated by Django 5.0 on 2024-03-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_patientfeedback_reception'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientFeedback',
        ),
    ]
