# Generated by Django 5.0 on 2024-03-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_patientfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='non_registered_patient_name',
            new_name='fullname_patient',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='non_registered_patient_contact',
            new_name='patient_contact',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='non_registered_patient_indevid_intevicat_nomer',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='patient_name',
        ),
    ]
