# Generated by Django 5.0 on 2024-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_non_registered_patient_name_reception_fullname_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
    ]
