# Generated by Django 5.0 on 2024-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_reception_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='fullname_patient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО пациента'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакты пациента'),
        ),
    ]
