# Generated by Django 5.0 on 2024-04-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_doctor_facebook_url_doctor_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Диагноз', 'verbose_name_plural': 'Диагноз'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врачи', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='equipmentservicehistory',
            options={'verbose_name': 'Обслуживание', 'verbose_name_plural': 'Обслуживании'},
        ),
        migrations.AlterModelOptions(
            name='medicalequipment',
            options={'verbose_name': 'Инвентарь', 'verbose_name_plural': 'Инвентаризация'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='trainingequipment',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Зал'},
        ),
        migrations.DeleteModel(
            name='PatientMedicalHistory',
        ),
    ]
