# Generated by Django 5.0 on 2024-04-07 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_diagnosis_options_alter_doctor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Примечание', 'verbose_name_plural': 'Примечаний'},
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='treatment_text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='masseur',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='masseur_images/', verbose_name='Фотография врача'),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения инструктура')),
                ('image', models.ImageField(default='', null=True, upload_to='trainer_images/', verbose_name='Фотография инструктура')),
                ('bio', models.TextField(default='', null=True, verbose_name='Информация о инструктура')),
                ('specialization_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='main.specializationcategory', verbose_name='Категория специальности')),
                ('trainer_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
            },
        ),
        migrations.AddField(
            model_name='reception',
            name='trainer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trainer', verbose_name='Инструктор'),
        ),
    ]
