# Generated by Django 5.0 on 2024-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_diagnosis_text_kz_diagnosis_diagnosis_text_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masseur',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='masseur',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='masseur',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram URL'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram URL'),
        ),
    ]
