# Generated by Django 5.0 on 2024-04-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_masseur_facebook_url_masseur_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctors_name_kk',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctors_name_ru',
        ),
        migrations.RemoveField(
            model_name='masseur',
            name='masseur_name_kk',
        ),
        migrations.RemoveField(
            model_name='masseur',
            name='masseur_name_ru',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='comed_kk',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='comed_ru',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='declined_kk',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='declined_ru',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='fullname_patient_kk',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='fullname_patient_ru',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='is_confirmed_kk',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='is_confirmed_ru',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='no_show_kk',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='no_show_ru',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='patient_contact_kk',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='patient_contact_ru',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='payment_confirmed_kk',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='payment_confirmed_ru',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='requires_massage_kk',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='requires_massage_ru',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_name_kk',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_name_ru',
        ),
    ]
